name: CI

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: false

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'  # Run every day at 1:00 AM

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Install JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-disabled: true

      - name: Update README
        run: |-
          ./gradlew --no-daemon --console=plain run --args="-o README.md"
          cat README.md

      - name: (Fail-only) Upload the build report
        if: failure()
        uses: actions/upload-artifact@v6
        with:
          name: error-report
          path: build-reports.zip
          if-no-files-found: ignore

      - name: Commit and push if changed
        if: github.event_name != 'pull_request'
        run: |-
          git diff
          git config --global user.email "actions@users.noreply.github.com"
          git config --global user.name "README-bot"
          git add -A
          git commit -m "Updated content" || exit 0
          git fetch origin main
          git pull --rebase origin main
          git push

  update-readme:
    name: WakaReadme Update
    if: github.event_name != 'pull_request'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: main

      # this action name
      - uses: athul/waka-readme@master # do NOT replace with anything else
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }} # required
          ### content
          SHOW_TITLE: true # optional
          SECTION_NAME: waka # optional
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿ # optional
          CODE_LANG: kotlin # optional
          TIME_RANGE: all_time # optional
          LANG_COUNT: 10 # optional
          SHOW_TIME: true # optional
          SHOW_TOTAL: true # optional
          SHOW_MASKED_TIME: false # optional
          STOP_AT_OTHER: false # optional
          IGNORED_LANGUAGES: YAML JSON TOML # optional
          ### commit
          #COMMIT_MESSAGE: Updated waka-readme graph with new metrics # optional
          #TARGET_BRANCH: master # optional
          #TARGET_PATH: README.md # optional
          #COMMITTER_NAME: GitHubActionBot # optional
          #COMMITTER_EMAIL: action-bot@github.com # optional
          #AUTHOR_NAME: YOUR_NAME # optional
          #AUTHOR_EMAIL: YOUR@EMAIL.com # optional
          # you can populate email-id with secrets instead
